### ISSUE TITLE
Won't work with vscode + prettier

### ISSUE THREAD

**Issue by dacrypt** [ionic-team/eslint-plugin#1]
Error while loading rule '@typescript-eslint/no-unnecessary-type-assertion '/src/app/app.component.ts:: You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Occurred while linting /src/app/app.component.ts

**Comment by imhoffd** [comment]
This plugin is deprecated. Ionic/Capacitor/Stencil are now using the following:
- https://github.com/ionic-team/prettier-config
- https://github.com/ionic-team/eslint-config
