### ISSUE TITLE
Replace no-shadow with typescript no-shadow rule

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/eslint-plugin#2]
According to this doc: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-shadow.md

**Comment by imhoffd** [comment]
This plugin is deprecated. Ionic/Capacitor/Stencil are now using the following:
- https://github.com/ionic-team/prettier-config
- https://github.com/ionic-team/eslint-config
